import { ORCHESTRATOR_ONLY, mcpTool, type ToolSpec } from "./types.js";

export const TOOL_DEFINITIONS = [
  {
    id: "state_check_project",
    mcp: mcpTool("state_check_project", true),
    title: "Check project state",
    description: "Read consumer state and report setup completeness plus the next route.",
    stage: "orchestration",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: [],
    sideEffects: ["read_only"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Consumer cwd may or may not contain .generate-ads-img state."],
    failureModes: ["State files are malformed or unreadable."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/check-state.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/check-state.mjs",
    },
  },
  {
    id: "artifact_validate",
    mcp: mcpTool("artifact_validate", true),
    title: "Validate artifact shape",
    description: "Run the schema validator for a stage artifact or validator family member.",
    stage: "orchestration",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: ["schemas/**/*.schema.json"],
    sideEffects: ["read_only"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["A target artifact path and validator kind are known."],
    failureModes: ["Schema fails, validator usage is incomplete, or schema file is missing."],
    currentImplementation: {
      kind: "validator-family",
      path: "shared/validators",
      command: "npx tsx ${CLAUDE_PLUGIN_ROOT}/shared/validators/validate-*.ts <artifact>",
    },
  },
  {
    id: "orchestration_validate_subagent_projection",
    mcp: mcpTool("orchestration_validate_subagent_projection", true, "handoff_validate"),
    title: "Validate subagent projection",
    description: "Validate a materialized JSON handoff before dispatch so raw media, browser logs, credentials, or wrong-persona data do not leak.",
    stage: "orchestration",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: [],
    sideEffects: ["read_only"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["A materialized handoff JSON exists for a target agent."],
    failureModes: ["Projection guard rejects forbidden keys, raw media paths, forbidden artifacts, or other-persona scope."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/validate-subagent-projection.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/validate-subagent-projection.mjs <agent_name> <handoff.json> [--persona <persona_id>]",
    },
  },
  {
    id: "collection_run_flow",
    mcp: mcpTool("collection_run_flow", true),
    title: "Run public ad-library collection flow",
    description: "Run the source flow through the managed CDP lifecycle and write collected ad creatives.",
    stage: "collection",
    priority: "P0",
    inputSchemaRef: "schemas/collection/keyword-plan.schema.json",
    outputSchemaRef: "schemas/collection/ad-creative.schema.json",
    artifactSchemaRefs: ["schemas/collection/ad-creative.schema.json", "schemas/collection/run-manifest.schema.json"],
    sideEffects: ["write_state", "network_public", "cdp_public_browser", "spawn_chrome"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Setup state exists.", "Source and flow mode are selected.", "Public ad-transparency collection is allowed."],
    failureModes: ["Public site block/verification, no advertiser match, no creatives, CDP launch failure, invalid output schema."],
    currentImplementation: {
      kind: "cli",
      path: "shared/collect/run-flow.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/collect/run-flow.mjs <source> <persona_id> <mode> <query> <run_id> [--from-keyword-plan <plan.json>]",
    },
  },
  {
    id: "collection_select_images",
    mcp: mcpTool("collection_select_images", true),
    title: "Serve human image keep/delete review",
    description: "Serve the localhost review grid, write the human screening artifact, move unselected images to _removed, and advance the run stage.",
    stage: "collection",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: "schemas/collection/image-screening.schema.json",
    artifactSchemaRefs: ["schemas/collection/image-screening.schema.json"],
    sideEffects: ["write_state", "move_files", "serve_localhost"],
    requiresUserConfirmation: true,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["A collected run exists with ad creative images."],
    failureModes: ["No browser/display fallback needed, malformed creative set, localhost server failure, image move/write failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/collect/select-images.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/collect/select-images.mjs <run_id> <persona_id>",
    },
  },
  {
    id: "collection_screen_images",
    mcp: mcpTool("collection_screen_images", true),
    title: "Screen mechanically unusable images",
    description: "Apply deterministic size/dimension/duplicate screening after the human keep gate.",
    stage: "collection",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: "schemas/collection/image-screening.schema.json",
    artifactSchemaRefs: ["schemas/collection/image-screening.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Run stage is human_reviewed.", "Human screening JSON exists."],
    failureModes: ["Images directory missing, screening artifact invalid, stage advance failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/collect/screen-images.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/collect/screen-images.mjs <run_id> <persona_id> <imagesDir>",
    },
  },
  {
    id: "analysis_close_run",
    mcp: mcpTool("analysis_close_run", true),
    title: "Close analysis run",
    description: "Persist per-ad lineage envelopes, freeze the run-local creative snapshot while the store is current, and advance the run to analyzed.",
    stage: "analysis",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: ["schemas/lineage/artifact-envelope.schema.json", "schemas/analysis/creative-snapshot.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Per-kind analysis staging exists for the run.", "Run manifest exists."],
    failureModes: ["Empty staging, missing manifest, malformed envelopes, creative snapshot freeze failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/close-analysis.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/close-analysis.mjs <run_id> [stateDir]",
    },
  },
  {
    id: "analysis_validate_store",
    mcp: mcpTool("analysis_validate_store", true),
    title: "Validate analysis store",
    description: "Validate the durable persona lineage store before generation or creative-change edge analysis.",
    stage: "analysis",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: ["schemas/lineage/artifact-envelope.schema.json"],
    sideEffects: ["read_only"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Persona id is known."],
    failureModes: ["Store is absent, empty, contains raw payloads, partial envelopes, or missing logic_version."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/validate-store.ts",
      command: "npx tsx ${CLAUDE_PLUGIN_ROOT}/shared/harness/validate-store.ts <persona_id>",
    },
  },
  {
    id: "analysis_build_market_position",
    mcp: mcpTool("analysis_build_market_position", true),
    title: "Build market-position matrix",
    description: "Build the benefit-by-funnel market-position matrix from analysis staging or the durable store.",
    stage: "analysis",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: "schemas/analysis/market-position-matrix.schema.json",
    artifactSchemaRefs: ["schemas/analysis/market-position-matrix.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Persona id is known.", "Store mode requires a validated durable store."],
    failureModes: ["No store, no strategy/ad-type envelopes, corrupt envelopes, schema failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/collect/build-market-position.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/collect/build-market-position.mjs --from-store <persona_id> <out>",
    },
  },
  {
    id: "generation_normalize_artifact",
    mcp: mcpTool("generation_normalize_artifact", true),
    title: "Normalize generation artifact envelope",
    description: "Conservatively conform known drift-prone generation artifacts without rewriting creative substance.",
    stage: "generation",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: ["schemas/generation/creative-brief.schema.json", "schemas/generation/critic-verdict.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Artifact kind and file path are known."],
    failureModes: ["Unknown kind no-ops, JSON parse failure, write failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/normalize-artifact.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/normalize-artifact.mjs <kind> <file>",
    },
  },
  {
    id: "generation_finalize_candidates",
    mcp: mcpTool("generation_finalize_candidates", true),
    title: "Finalize prompt candidates",
    description: "Join copy-layout, provider prompt outputs, and critic verdicts into final candidate artifacts.",
    stage: "generation",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: "schemas/generation/creative-candidate.schema.json",
    artifactSchemaRefs: ["schemas/generation/creative-candidate.schema.json", "schemas/generation/candidate-selection-log.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Copy-layout, ChatGPT adapter output, Gemini adapter output, and critic verdict exist."],
    failureModes: ["Schema mismatch, byte-identical provider outputs, no passing candidates, write failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/finalize-candidates.ts",
      command: "npx tsx ${CLAUDE_PLUGIN_ROOT}/shared/harness/finalize-candidates.ts --copy <copy-layout.json> --chatgpt <chatgpt.json> --gemini <gemini.json> --out <out_dir>",
    },
  },
  {
    id: "generation_validate_run",
    mcp: mcpTool("generation_validate_run", true),
    title: "Validate generation run",
    description: "Validate every artifact produced by a prompt-candidate generation run before presentation.",
    stage: "generation",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: ["schemas/generation/*.schema.json", "schemas/analysis/market-position-matrix.schema.json"],
    sideEffects: ["read_only"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Generation run directory exists."],
    failureModes: ["Missing mandatory bridge artifacts, non-conformant JSON, extra fields, skipped deterministic producer."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/validate-gen-run.ts",
      command: "npx tsx ${CLAUDE_PLUGIN_ROOT}/shared/harness/validate-gen-run.ts <run_dir>",
    },
  },
  {
    id: "recipe_serve_viewer",
    mcp: mcpTool("recipe_serve_viewer", true),
    title: "Serve recipe validation viewer",
    description: "Serve a read-only localhost HTML viewer for human comparison of ads and extracted recipes.",
    stage: "reporting",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: [],
    sideEffects: ["serve_localhost"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["At least one analyzed or collected run exists for the persona."],
    failureModes: ["No runs, invalid store/read data, localhost server failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/collect/validate-recipe.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/collect/validate-recipe.mjs <persona_id>",
    },
  },
  {
    id: "report_aggregate_competitive_trend",
    mcp: mcpTool("report_aggregate_competitive_trend", true),
    title: "Aggregate competitive trend",
    description: "Aggregate longevity, variation, and change signals across dated public ad snapshots.",
    stage: "reporting",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: "schemas/analysis/competitive-trend.schema.json",
    artifactSchemaRefs: ["schemas/analysis/competitive-trend.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["At least one collection snapshot exists for the persona."],
    failureModes: ["No snapshots, missing dates, schema failure, insufficient data for change claims."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/run-competitive-trend.ts",
      command: "npx tsx ${CLAUDE_PLUGIN_ROOT}/shared/harness/run-competitive-trend.ts <persona_id> <run_id> [today_iso]",
    },
  },
  {
    id: "report_render_competitive",
    mcp: mcpTool("report_render_competitive", true),
    title: "Render competitive report",
    description: "Render the competitive trend report HTML from the validated report payload.",
    stage: "reporting",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: ["schemas/analysis/competitive-trend.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Competitive trend JSON exists."],
    failureModes: ["Invalid payload, template render failure, write failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/render-report.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/render-report.mjs <competitive-trend.json> [out.html]",
    },
  },
  {
    id: "creative_change_build_snapshot",
    mcp: mcpTool("creative_change_build_snapshot", true),
    title: "Build creative-change snapshot",
    description: "Build a comparable run-level creative snapshot from collected creatives and durable store envelopes.",
    stage: "analysis",
    priority: "P0",
    inputSchemaRef: null,
    outputSchemaRef: "schemas/analysis/creative-snapshot.schema.json",
    artifactSchemaRefs: ["schemas/analysis/creative-snapshot.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Collection snapshot exists.", "Durable store validates.", "Selected run can join to store envelopes."],
    failureModes: ["No collection snapshot, no store, low join coverage, schema failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/build-creative-snapshot.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/build-creative-snapshot.mjs <persona_id> <run_id> [out_run_id]",
    },
  },
  {
    id: "creative_change_compare_snapshots",
    mcp: mcpTool("creative_change_compare_snapshots", true),
    title: "Compare creative snapshots",
    description: "Compute inventory, update, distribution, and coverage deltas between two frozen creative snapshots.",
    stage: "analysis",
    priority: "P0",
    inputSchemaRef: "schemas/analysis/creative-snapshot.schema.json",
    outputSchemaRef: "schemas/analysis/creative-diff.schema.json",
    artifactSchemaRefs: ["schemas/analysis/creative-diff.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Two comparable snapshots are selected."],
    failureModes: ["Fewer than two snapshots, missing frozen FROM snapshot, schema failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/compare-creative-snapshots.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/compare-creative-snapshots.mjs <from_snapshot.json> <to_snapshot.json> [out.json]",
    },
  },
  {
    id: "creative_change_detect_candidates",
    mcp: mcpTool("creative_change_detect_candidates", true),
    title: "Detect creative-change candidates",
    description: "Promote material computed diff signals into deterministic change candidates before agent interpretation.",
    stage: "analysis",
    priority: "P0",
    inputSchemaRef: "schemas/analysis/creative-diff.schema.json",
    outputSchemaRef: "schemas/analysis/change-candidate.schema.json",
    artifactSchemaRefs: ["schemas/analysis/change-candidate.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Creative diff exists."],
    failureModes: ["Low confidence capped, missing audience_read suppresses audience shifts, schema failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/detect-change-candidates.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/detect-change-candidates.mjs <creative-diff.json> [out.json]",
    },
  },
  {
    id: "creative_change_render_report",
    mcp: mcpTool("creative_change_render_report", true),
    title: "Render creative-change report",
    description: "Validate the creative-change report payload and render escaped HTML with supporting evidence.",
    stage: "reporting",
    priority: "P0",
    inputSchemaRef: "schemas/analysis/creative-change-report.schema.json",
    outputSchemaRef: null,
    artifactSchemaRefs: ["schemas/analysis/creative-change-report.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Creative-change report JSON exists."],
    failureModes: ["Invalid report payload, missing supporting context, HTML render/write failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/render-change-report.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/harness/render-change-report.mjs <creative-change-report.json> [out.html]",
    },
  },
  {
    id: "collection_build_queries",
    mcp: mcpTool("collection_build_queries", false),
    title: "Build fallback collection queries",
    description: "Derive deterministic query combinations from product, keyword model, or competitor signals.",
    stage: "collection",
    priority: "P1",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: [],
    sideEffects: ["read_only"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Product/persona context or keyword model exists."],
    failureModes: ["No usable model or competitor seeds."],
    currentImplementation: {
      kind: "module",
      path: "shared/collect/scout-rank.mjs",
      notes: "deriveQueries and ranking helpers are internal today; no stable CLI tool boundary yet.",
    },
  },
  {
    id: "collection_refine_detail_cuts",
    mcp: mcpTool("collection_refine_detail_cuts", false),
    title: "Refine detail-cut images",
    description: "Mechanically prepare own/user-provided detail cuts around the ad-creative refiner path.",
    stage: "collection",
    priority: "P1",
    inputSchemaRef: null,
    outputSchemaRef: "schemas/collection/ad-creative.schema.json",
    artifactSchemaRefs: ["schemas/collection/ad-creative.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Own or user-provided image paths exist."],
    failureModes: ["Missing assets, unsupported format, schema failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/collect/refine-images.mjs",
      command: "node ${CLAUDE_PLUGIN_ROOT}/shared/collect/refine-images.mjs <args>",
    },
  },
  {
    id: "analysis_compute_bindings",
    mcp: mcpTool("analysis_compute_bindings", false),
    title: "Compute copy-layout bindings",
    description: "Compute text-to-graphic overlap bindings after perception and slice stitching.",
    stage: "analysis",
    priority: "P1",
    inputSchemaRef: "schemas/analysis/perception.schema.json",
    outputSchemaRef: "schemas/analysis/bindings.schema.json",
    artifactSchemaRefs: ["schemas/analysis/bindings.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Perception artifact exists."],
    failureModes: ["Malformed boxes, missing perception, schema failure."],
    currentImplementation: {
      kind: "module",
      path: "shared/collect/bbox-bind.mjs",
    },
  },
  {
    id: "analysis_run_ad_type_gate",
    mcp: mcpTool("analysis_run_ad_type_gate", false),
    title: "Run ad-type gate",
    description: "Check whether a classified ad delivers the deterministic requirements of its ad type.",
    stage: "analysis",
    priority: "P1",
    inputSchemaRef: "schemas/analysis/ad-type.schema.json",
    outputSchemaRef: "schemas/analysis/ad-type-gate.schema.json",
    artifactSchemaRefs: ["schemas/analysis/ad-type-gate.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Ad type and downstream analyses exist."],
    failureModes: ["Unknown ad_type, missing required evidence, schema failure."],
    currentImplementation: {
      kind: "module",
      path: "shared/collect/ad-type-gate.mjs",
    },
  },
  {
    id: "analysis_run_keyword_model",
    mcp: mcpTool("analysis_run_keyword_model", false),
    title: "Run keyword model",
    description: "Rank extracted keyword instances into the deterministic per-persona keyword model.",
    stage: "analysis",
    priority: "P1",
    inputSchemaRef: "schemas/analysis/keyword-instance.schema.json",
    outputSchemaRef: "schemas/analysis/keyword-model.schema.json",
    artifactSchemaRefs: ["schemas/analysis/keyword-model.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Keyword instances and corpus exist."],
    failureModes: ["Invalid instances, empty corpus, schema failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/run-keyword-model.ts",
      command: "npx tsx ${CLAUDE_PLUGIN_ROOT}/shared/harness/run-keyword-model.ts <instancesPath> <corpusPath> [personaPath] [outPath]",
    },
  },
  {
    id: "analysis_run_ad_pattern",
    mcp: mcpTool("analysis_run_ad_pattern", false),
    title: "Run ad-pattern aggregate",
    description: "Aggregate layout and copy analyses into deterministic ad-pattern signals.",
    stage: "analysis",
    priority: "P1",
    inputSchemaRef: null,
    outputSchemaRef: "schemas/analysis/ad-pattern.schema.json",
    artifactSchemaRefs: ["schemas/analysis/ad-pattern.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Layout and copy analysis envelopes exist."],
    failureModes: ["Invalid analysis envelopes, empty inputs, schema failure."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/run-ad-pattern.ts",
      command: "npx tsx ${CLAUDE_PLUGIN_ROOT}/shared/harness/run-ad-pattern.ts <layoutAnalysesPath> <copyAnalysesPath> <product_id> [synthesis] [outPath]",
    },
  },
  {
    id: "asset_cleanup_product_cutout",
    mcp: mcpTool("asset_cleanup_product_cutout", false),
    title: "Clean product cutout asset",
    description: "Create or report a transparent product cutout/cleanup result for generation inputs.",
    stage: "asset",
    priority: "P1",
    inputSchemaRef: "schemas/setup/product-asset.schema.json",
    outputSchemaRef: "schemas/setup/product-asset.schema.json",
    artifactSchemaRefs: ["schemas/setup/product-asset.schema.json"],
    sideEffects: ["write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Product asset registry exists."],
    failureModes: ["Missing sharp dependency, missing source image, unsupported format; may degrade to report-only."],
    currentImplementation: {
      kind: "cli",
      path: "shared/harness/product-cutout-cleanup.ts",
      command: "npx tsx ${CLAUDE_PLUGIN_ROOT}/shared/harness/product-cutout-cleanup.ts --assets <product-assets.json> [--product-id <id>] [--source <path>] [--out <path>]",
    },
  },
  {
    id: "lineage_record_logic_change",
    mcp: mcpTool("lineage_record_logic_change", false),
    title: "Record logic change",
    description: "Record a logic-change audit entry and compute impacted stale artifacts.",
    stage: "lineage",
    priority: "P1",
    inputSchemaRef: "schemas/lineage/logic-change.schema.json",
    outputSchemaRef: "schemas/lineage/logic-change.schema.json",
    artifactSchemaRefs: ["schemas/lineage/logic-change.schema.json"],
    sideEffects: ["audit_log", "write_state"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Human verdict or QA finding identifies a logic change."],
    failureModes: ["Missing finding or commit sha, invalid scope, schema failure."],
    currentImplementation: {
      kind: "module",
      path: "shared/lineage/logic-change-log.mjs",
    },
  },
  {
    id: "lineage_list_stale_artifacts",
    mcp: mcpTool("lineage_list_stale_artifacts", false),
    title: "List stale lineage artifacts",
    description: "List artifacts made stale by a logic-version change for a scope.",
    stage: "lineage",
    priority: "P1",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: [],
    sideEffects: ["read_only"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Store index exists or absence is acceptable."],
    failureModes: ["Corrupt index or malformed envelopes."],
    currentImplementation: {
      kind: "module",
      path: "shared/lineage/staleness.mjs",
    },
  },
  {
    id: "creative_change_evaluate_agent_output",
    mcp: mcpTool("creative_change_evaluate_agent_output", false, "creative_change_eval_output"),
    title: "Evaluate creative-change agent output",
    description: "Programmatically gate temporal-change-analyst outputs for schema, candidate refs, number fidelity, and overclaim boundaries.",
    stage: "analysis",
    priority: "P1",
    inputSchemaRef: null,
    outputSchemaRef: null,
    artifactSchemaRefs: [
      "schemas/analysis/creative-diff.schema.json",
      "schemas/analysis/change-candidate.schema.json",
      "schemas/analysis/interpreted-change-event.schema.json",
      "schemas/analysis/creative-change-report.schema.json",
    ],
    sideEffects: ["read_only"],
    requiresUserConfirmation: false,
    callableBy: ORCHESTRATOR_ONLY,
    preconditions: ["Diff, candidates, interpreted events, and report payload exist."],
    failureModes: ["Unknown candidate ids, invented numbers, positive performance/causal/persona overclaims, missing context flags."],
    currentImplementation: {
      kind: "module",
      path: "shared/collect/creative-change-agent-eval.mjs",
      notes: "Module evaluator today; promote to CLI or handler in a later PR if needed.",
    },
  },
] as const satisfies readonly ToolSpec[];
